# config/packages/messenger.yaml
framework:
    messenger:
        default_bus: messenger.bus.default
        transports:
            async:
                dsn: 'in-memory://'
        routing:
            'App\Message\SendEmailMessage': async
